apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: 421089506438.dkr.ecr.eu-west-1.amazonaws.com/demo-ecr:0.0.1
          ports:
            - containerPort: 9999
