---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: 421089506438.dkr.ecr.eu-west-1.amazonaws.com/demo-ecr:0.0.1
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: "service-helloworld"
spec:
  selector:
    app: helloworld
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 9999
